import logging

def calculate_sci_score(prompt, response):
    """
Calculate the SCI-Score for a given response.

Args:
    prompt (str): The text of the question sent to the model.
    response (str): The answer generated by the model.

Returns:
    float: The calculated SCI-Score.
"""
    if not prompt.strip() or not response.strip():
        return 0.0
    try:
        # Score calculation logic (simplified for now)
        score = len(response) / (len(prompt) + 1)  # Exemple simple
        return round(score, 2)
    except Exception as e:
        logging.error(f"if we have a error in the calcul : {e}")
        return 0.0