name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 black

    - name: Run pylint
      run: pylint project_name/

    - name: Run flake8
      run: flake8 project_name/

    - name: Check formatting with black
      run: black --check project_name/
