name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
    paths:
      - "**/*.puml"
  workflow_dispatch:

jobs:
  plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get changed UML files
        id: getfile
        run: |
          FILES=$(git diff --name-only HEAD^ HEAD | grep .puml || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Generate SVG Diagrams
        if: steps.getfile.outputs.files != ''
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}

      - name: Push Local Changes
        if: steps.getfile.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
